/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BatchReunionsRouteImport } from './routes/batch-reunions'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CorporateConclavesRouteImport } from './routes/corporate-conclaves'
import { Route as CruisesRouteImport } from './routes/cruises'
import { Route as FlightsRouteImport } from './routes/flights'
import { Route as ForeignTravelCardRouteImport } from './routes/foreign-travel-card'
import { Route as GolfTourismRouteImport } from './routes/golf-tourism'
import { Route as HoneymoonRouteImport } from './routes/honeymoon'
import { Route as HotelsRouteImport } from './routes/hotels'
import { Route as PackagesRouteImport } from './routes/packages'
import { Route as SeniorCitizensRouteImport } from './routes/senior-citizens'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as VisaRouteImport } from './routes/visa'
import { Route as PackagesIndexRouteImport } from './routes/packages.index'
import { Route as PackagesRegionRouteImport } from './routes/packages.$region'
import { Route as PackagesRegionIndexRouteImport } from './routes/packages.$region.index'
import { Route as PackagesRegionSlugRouteImport } from './routes/packages.$region.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BatchReunionsRoute = BatchReunionsRouteImport.update({
  id: '/batch-reunions',
  path: '/batch-reunions',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CorporateConclavesRoute = CorporateConclavesRouteImport.update({
  id: '/corporate-conclaves',
  path: '/corporate-conclaves',
  getParentRoute: () => rootRouteImport,
} as any)
const CruisesRoute = CruisesRouteImport.update({
  id: '/cruises',
  path: '/cruises',
  getParentRoute: () => rootRouteImport,
} as any)
const FlightsRoute = FlightsRouteImport.update({
  id: '/flights',
  path: '/flights',
  getParentRoute: () => rootRouteImport,
} as any)
const ForeignTravelCardRoute = ForeignTravelCardRouteImport.update({
  id: '/foreign-travel-card',
  path: '/foreign-travel-card',
  getParentRoute: () => rootRouteImport,
} as any)
const GolfTourismRoute = GolfTourismRouteImport.update({
  id: '/golf-tourism',
  path: '/golf-tourism',
  getParentRoute: () => rootRouteImport,
} as any)
const HoneymoonRoute = HoneymoonRouteImport.update({
  id: '/honeymoon',
  path: '/honeymoon',
  getParentRoute: () => rootRouteImport,
} as any)
const HotelsRoute = HotelsRouteImport.update({
  id: '/hotels',
  path: '/hotels',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesRoute = PackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => rootRouteImport,
} as any)
const SeniorCitizensRoute = SeniorCitizensRouteImport.update({
  id: '/senior-citizens',
  path: '/senior-citizens',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const VisaRoute = VisaRouteImport.update({
  id: '/visa',
  path: '/visa',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesIndexRoute = PackagesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PackagesRoute,
} as any)
const PackagesRegionRoute = PackagesRegionRouteImport.update({
  id: '/$region',
  path: '/$region',
  getParentRoute: () => PackagesRoute,
} as any)
const PackagesRegionIndexRoute = PackagesRegionIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PackagesRegionRoute,
} as any)
const PackagesRegionSlugRoute = PackagesRegionSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => PackagesRegionRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/batch-reunions': typeof BatchReunionsRoute
  '/contact': typeof ContactRoute
  '/corporate-conclaves': typeof CorporateConclavesRoute
  '/cruises': typeof CruisesRoute
  '/flights': typeof FlightsRoute
  '/foreign-travel-card': typeof ForeignTravelCardRoute
  '/golf-tourism': typeof GolfTourismRoute
  '/honeymoon': typeof HoneymoonRoute
  '/hotels': typeof HotelsRoute
  '/packages': typeof PackagesRouteWithChildren
  '/senior-citizens': typeof SeniorCitizensRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/visa': typeof VisaRoute
  '/packages/$region': typeof PackagesRegionRouteWithChildren
  '/packages/': typeof PackagesIndexRoute
  '/packages/$region/$slug': typeof PackagesRegionSlugRoute
  '/packages/$region/': typeof PackagesRegionIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/batch-reunions': typeof BatchReunionsRoute
  '/contact': typeof ContactRoute
  '/corporate-conclaves': typeof CorporateConclavesRoute
  '/cruises': typeof CruisesRoute
  '/flights': typeof FlightsRoute
  '/foreign-travel-card': typeof ForeignTravelCardRoute
  '/golf-tourism': typeof GolfTourismRoute
  '/honeymoon': typeof HoneymoonRoute
  '/hotels': typeof HotelsRoute
  '/senior-citizens': typeof SeniorCitizensRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/visa': typeof VisaRoute
  '/packages': typeof PackagesIndexRoute
  '/packages/$region/$slug': typeof PackagesRegionSlugRoute
  '/packages/$region': typeof PackagesRegionIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/batch-reunions': typeof BatchReunionsRoute
  '/contact': typeof ContactRoute
  '/corporate-conclaves': typeof CorporateConclavesRoute
  '/cruises': typeof CruisesRoute
  '/flights': typeof FlightsRoute
  '/foreign-travel-card': typeof ForeignTravelCardRoute
  '/golf-tourism': typeof GolfTourismRoute
  '/honeymoon': typeof HoneymoonRoute
  '/hotels': typeof HotelsRoute
  '/packages': typeof PackagesRouteWithChildren
  '/senior-citizens': typeof SeniorCitizensRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/visa': typeof VisaRoute
  '/packages/$region': typeof PackagesRegionRouteWithChildren
  '/packages/': typeof PackagesIndexRoute
  '/packages/$region/$slug': typeof PackagesRegionSlugRoute
  '/packages/$region/': typeof PackagesRegionIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/batch-reunions'
    | '/contact'
    | '/corporate-conclaves'
    | '/cruises'
    | '/flights'
    | '/foreign-travel-card'
    | '/golf-tourism'
    | '/honeymoon'
    | '/hotels'
    | '/packages'
    | '/senior-citizens'
    | '/sitemap.xml'
    | '/visa'
    | '/packages/$region'
    | '/packages/'
    | '/packages/$region/$slug'
    | '/packages/$region/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/batch-reunions'
    | '/contact'
    | '/corporate-conclaves'
    | '/cruises'
    | '/flights'
    | '/foreign-travel-card'
    | '/golf-tourism'
    | '/honeymoon'
    | '/hotels'
    | '/senior-citizens'
    | '/sitemap.xml'
    | '/visa'
    | '/packages'
    | '/packages/$region/$slug'
    | '/packages/$region'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/batch-reunions'
    | '/contact'
    | '/corporate-conclaves'
    | '/cruises'
    | '/flights'
    | '/foreign-travel-card'
    | '/golf-tourism'
    | '/honeymoon'
    | '/hotels'
    | '/packages'
    | '/senior-citizens'
    | '/sitemap.xml'
    | '/visa'
    | '/packages/$region'
    | '/packages/'
    | '/packages/$region/$slug'
    | '/packages/$region/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BatchReunionsRoute: typeof BatchReunionsRoute
  ContactRoute: typeof ContactRoute
  CorporateConclavesRoute: typeof CorporateConclavesRoute
  CruisesRoute: typeof CruisesRoute
  FlightsRoute: typeof FlightsRoute
  ForeignTravelCardRoute: typeof ForeignTravelCardRoute
  GolfTourismRoute: typeof GolfTourismRoute
  HoneymoonRoute: typeof HoneymoonRoute
  HotelsRoute: typeof HotelsRoute
  PackagesRoute: typeof PackagesRouteWithChildren
  SeniorCitizensRoute: typeof SeniorCitizensRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  VisaRoute: typeof VisaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/batch-reunions': {
      id: '/batch-reunions'
      path: '/batch-reunions'
      fullPath: '/batch-reunions'
      preLoaderRoute: typeof BatchReunionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corporate-conclaves': {
      id: '/corporate-conclaves'
      path: '/corporate-conclaves'
      fullPath: '/corporate-conclaves'
      preLoaderRoute: typeof CorporateConclavesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cruises': {
      id: '/cruises'
      path: '/cruises'
      fullPath: '/cruises'
      preLoaderRoute: typeof CruisesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flights': {
      id: '/flights'
      path: '/flights'
      fullPath: '/flights'
      preLoaderRoute: typeof FlightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/foreign-travel-card': {
      id: '/foreign-travel-card'
      path: '/foreign-travel-card'
      fullPath: '/foreign-travel-card'
      preLoaderRoute: typeof ForeignTravelCardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/golf-tourism': {
      id: '/golf-tourism'
      path: '/golf-tourism'
      fullPath: '/golf-tourism'
      preLoaderRoute: typeof GolfTourismRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/honeymoon': {
      id: '/honeymoon'
      path: '/honeymoon'
      fullPath: '/honeymoon'
      preLoaderRoute: typeof HoneymoonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotels': {
      id: '/hotels'
      path: '/hotels'
      fullPath: '/hotels'
      preLoaderRoute: typeof HotelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages': {
      id: '/packages'
      path: '/packages'
      fullPath: '/packages'
      preLoaderRoute: typeof PackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/senior-citizens': {
      id: '/senior-citizens'
      path: '/senior-citizens'
      fullPath: '/senior-citizens'
      preLoaderRoute: typeof SeniorCitizensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visa': {
      id: '/visa'
      path: '/visa'
      fullPath: '/visa'
      preLoaderRoute: typeof VisaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages/': {
      id: '/packages/'
      path: '/'
      fullPath: '/packages/'
      preLoaderRoute: typeof PackagesIndexRouteImport
      parentRoute: typeof PackagesRoute
    }
    '/packages/$region': {
      id: '/packages/$region'
      path: '/$region'
      fullPath: '/packages/$region'
      preLoaderRoute: typeof PackagesRegionRouteImport
      parentRoute: typeof PackagesRoute
    }
    '/packages/$region/': {
      id: '/packages/$region/'
      path: '/'
      fullPath: '/packages/$region/'
      preLoaderRoute: typeof PackagesRegionIndexRouteImport
      parentRoute: typeof PackagesRegionRoute
    }
    '/packages/$region/$slug': {
      id: '/packages/$region/$slug'
      path: '/$slug'
      fullPath: '/packages/$region/$slug'
      preLoaderRoute: typeof PackagesRegionSlugRouteImport
      parentRoute: typeof PackagesRegionRoute
    }
  }
}

interface PackagesRegionRouteChildren {
  PackagesRegionSlugRoute: typeof PackagesRegionSlugRoute
  PackagesRegionIndexRoute: typeof PackagesRegionIndexRoute
}

const PackagesRegionRouteChildren: PackagesRegionRouteChildren = {
  PackagesRegionSlugRoute: PackagesRegionSlugRoute,
  PackagesRegionIndexRoute: PackagesRegionIndexRoute,
}

const PackagesRegionRouteWithChildren = PackagesRegionRoute._addFileChildren(
  PackagesRegionRouteChildren,
)

interface PackagesRouteChildren {
  PackagesRegionRoute: typeof PackagesRegionRouteWithChildren
  PackagesIndexRoute: typeof PackagesIndexRoute
}

const PackagesRouteChildren: PackagesRouteChildren = {
  PackagesRegionRoute: PackagesRegionRouteWithChildren,
  PackagesIndexRoute: PackagesIndexRoute,
}

const PackagesRouteWithChildren = PackagesRoute._addFileChildren(
  PackagesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BatchReunionsRoute: BatchReunionsRoute,
  ContactRoute: ContactRoute,
  CorporateConclavesRoute: CorporateConclavesRoute,
  CruisesRoute: CruisesRoute,
  FlightsRoute: FlightsRoute,
  ForeignTravelCardRoute: ForeignTravelCardRoute,
  GolfTourismRoute: GolfTourismRoute,
  HoneymoonRoute: HoneymoonRoute,
  HotelsRoute: HotelsRoute,
  PackagesRoute: PackagesRouteWithChildren,
  SeniorCitizensRoute: SeniorCitizensRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  VisaRoute: VisaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
